### ISSUE TITLE
Incorrect RMSE calculation

### ISSUE THREAD

**Issue by kamileyagci** [learn-co-curriculum/dsc-gradient-descent-intro#1]
## Link to Canvas

https://learning.flatironschool.com/courses/1889/assignments/126282?module_item_id=261596

## Issue Subtype

- [ x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
def root_mean_squared_error(x_values, y_values, m, b):
    return round(math.sqrt(sum(squared_errors(x_values, y_values, m, b)))/len(x_values), 2)
```

### Concern

The RMSE calculation is incorrect. The 'len(x_values)' division should be inside the sqrt.

## (Optional) Proposed Solution

return round(math.sqrt(sum(squared_errors(x_values, y_values, m, b))/len(x_values)), 2) 

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
Thanks for opening this issue @kamileyagci :wave:, great catch on the RMSE definition. I have moved the division by the number of samples inside the square-root radical so the calculation is correct with commit 27e887f1dac75c046b0d9b9c006f9411b1aba27d. 

I am closing this issue at this time.
